### ISSUE TITLE
Numbers Format

### ISSUE THREAD

**Issue by aleschiro** [Beintoo/report-component-pivot#11]
Please remove ".00" after the integers

![schermata 2016-04-05 alle 09 29 58](https://cloud.githubusercontent.com/assets/18049464/14274342/03dbf8e8-fb11-11e5-9d33-f25dbb5c1f37.png)

**Comment by legentz** [comment]
![schermata 2016-04-06 alle 14 23 18](https://cloud.githubusercontent.com/assets/7389272/14316429/34920d18-fc03-11e5-874e-c2de1f6aeb07.png)

@aleschiro As you can see, there are two type of sum: integer and non-integer. So, it's normal to have the decimal form using **Sum** aggregator. If you wish to round your values, you can use the **Integer Sum** aggregator.
